### ISSUE TITLE
Fix old ratlas function in shiny tableau_atlas_couverture

### ISSUE THREAD

**Issue by BenMerSci** [ReseauBiodiversiteQuebec/tableau_atlas_couverture#1]
The shiny uses the function of ratlas version 1.0 -> need to change them to newer functions

**Comment by BenMerSci** [comment]
Waiting on review #2

**Comment by BenMerSci** [comment]
Have to branch ratlas to older version to be used for the apps, as newer version is bugging with httr2 with the OpenSSL error.

**Comment by vcameron1** [comment]
- [x] Update tableau to use `httr_v1` branch version of `ratlas`

**Comment by vcameron1** [comment]
Waiting for ubuntu 24.04 to fix issue
